#install packages
```{r}
#install.packages("gbm")
library('gbm') #generalized boosted models
library('caTools') #calculates AUC
#install.packages("ROCR")
library('ROCR') #makes ROC curves
#install.packages("dismo")
library('dismo')
library('caret')
library("dataRetrieval")
library(pdp)          # model visualization
library(ggplot2)      # model visualization
library(lime)         # model visualization
#install.packages("pROC")
library(pROC)
#install.packages("e1071", repos="http://R-Forge.R-project.org")
library("e1071")
library( MASS )    #    used to generate correlated variables
library( dplyr )
library( Hmisc )    #   used for graphing se bars
```

#read water quality data
```{r}
c<-"/Users/owner/Desktop/crypto/cry"
setwd(c)
cc<-read.csv("narrowresult.csv",header=T,sep=',')
#select cols
cc<-cc[,c("ActivityStartDate","MonitoringLocationIdentifier","ResultDetectionConditionText","CharacteristicName","ResultSampleFractionText", "ResultMeasureValue", "ResultMeasure.MeasureUnitCode","ResultCommentText","ResultLaboratoryCommentText","month")]
```

#read stations
```{r}
c_s<-"/Users/owner/Desktop/crypto/cry_station"
setwd(c_s)
cc_s<-read.csv("station.csv",header=T,sep=',')
head(cc_s)
dim(cc_s)
#select fields
cc_s<-cc_s[,c("MonitoringLocationIdentifier","DrainageAreaMeasure.MeasureValue","DrainageAreaMeasure.MeasureUnitCode", "ContributingDrainageAreaMeasure.MeasureValue","ContributingDrainageAreaMeasure.MeasureUnitCode", "LatitudeMeasure", "LongitudeMeasure")]
```

###change result of non-detect to zero
```{r}
as.data.frame(table(cc$ResultDetectionConditionText))
as.data.frame(table(cc[cc$ResultDetectionConditionText=="Not Detected",]$ResultMeasureValue))
as.data.frame(table(cc[cc$ResultDetectionConditionText=="",]$ResultMeasureValue))
cc$detect<-" "
cc[cc$ResultDetectionConditionText=="Not Detected",]$detect<-0
cc[cc$ResultDetectionConditionText=="",]$detect<-1
cc[as.character(cc$ResultMeasureValue)=="0",]$detect<-0

# cc$bi_result<-" "
# cc[as.numeric(cc$ResultMeasureValue)>0,]$bi_result<-1
# cc[as.numeric(cc$ResultMeasureValue)<=0,]$bi_result<-0

cc$r<-""
#cc$r<-as.numeric(cc$Q)/cc$DrainageAreaMeasure.MeasureValue
cc[cc$detect=="0",]$ResultMeasure.MeasureUnitCode
cc[cc$detect=="0",]$ResultMeasureValue
k<-which(cc$detect=="0")
{
  cc[k,]$ResultMeasureValue<-0
    cc[k,]$ResultMeasure.MeasureUnitCode<-"oocyst/10L"
  #USGS_cc4[i,]$oocyst10L<-as.numeric(as.character(USGS_cc4[i,]$ResultMeasureValue))
}
cc[cc$detect=="0",]$ResultMeasure.MeasureUnitCode
cc[cc$detect=="0",]$ResultMeasureValue
```

#find USGS "river" stations
```{r}
USGS_cc<-cc[grepl("USGS", cc$MonitoringLocationIdentifier)==T,]   
dim(USGS_cc)
USGS_cc$USGS<-USGS_cc$MonitoringLocationIdentifier

USGS_cc$USGS<-gsub('USGS-','',as.character(USGS_cc$USGS))
USGS_cc3<-USGS_cc[nchar(USGS_cc$USGS)==8,]

USGS_cc2<-merge(USGS_cc3,cc_s,by.x="MonitoringLocationIdentifier",by.y="MonitoringLocationIdentifier")

dim(USGS_cc)
dim(USGS_cc2)
dim(USGS_cc3)
save(USGS_cc2,file="/Users/owner/Desktop/crypto/USGS_cc2.Rdata")
```

#get discharge
```{r}
#cc_s$MonitoringLocationIdentifier
#cc_s$DrainageAreaMeasure.MeasureValue
USGS_cc2$Q<-" "
for (i in c(1:length(USGS_cc2$USGS)))

{
  
siteNo <- as.character(USGS_cc2[i,]$USGS)
pCode <- "00060" #discharge
#pCode shortName
#00060 Discharge [ft3/s]
#00065 Gage height [ft]
#00010 Temperature [C]
#00045 Precipitation [in]
#00400 pH
start.date <- as.character(USGS_cc2[i,]$ActivityStartDate)
end.date <- as.character(USGS_cc2[i,]$ActivityStartDate)
if (nrow(readNWISdv(siteNumbers = siteNo,
                     parameterCd = pCode,
                     startDate = start.date,
                     endDate = end.date))>0)
{
  USGS_cc2[i,]$Q<- readNWISdv(siteNumbers = siteNo,
                     parameterCd = pCode,
                     startDate = start.date,
                     endDate = end.date)$X_00060_00003
}
else
{
 USGS_cc2[i,]$Q<-NA 
}
  }
head(USGS_cc2)

```

#get runoff
```{r}
USGS_cc4<-USGS_cc2[is.na(USGS_cc2$Q)==F,]
USGS_cc4$runoff<-""
#ft s/sq mi
#1 mi = 5280 ft.
USGS_cc4$runoff<-(as.numeric(USGS_cc4$Q)*86400)/((USGS_cc4$DrainageAreaMeasure.MeasureValue)*5280*5280)*(0.3048*1000) #mm/d
summary(USGS_cc4$runoff)
  save(USGS_cc4,file="/Users/owner/Desktop/crypto/USGS_cc4_20190507.Rdata")
```

#hysep function to separate runoff
```{r}

hysep <- function(Flow, Dates, Start=NULL, End=NULL, da,
                 select="sliding", STAID="Unknown") {
  ## Start of code: initial processing
  STAID <- as.character(STAID[1L])
  if(is.null(Start))
    Start <- Dates[1L]
  else if(is.character(Start))
    Start <- as.Date(Start)
  if(is.null(End))
    End <- Dates[length(Dates)]
  else if(is.character(End))
    End <- as.Date(End)
  sel <- (Dates >= Start) & (Dates <= End)
  Dates <- Dates[sel]
  Flow <- pmax(Flow[sel], 1e-99) # Convert 0 to a small number
  if(any(is.na(Flow)))
    stop("Missing values between ", Start, " and ", End)
  if(any(diff(as.double(Dates)) != 1))
    stop("Date data are not continuous between Start and End")
  select <- match.arg(select, c("sliding", "local minimum", "fixed"))
  Nact <- max(da^0.2, 1)
  N2star <- max((((2*Nact) ) %/% 2)*2 + 1, 3)
  ## Set up for fixed--construct intervals of length N2star
  Nobs <- length(Flow)
  Ngrp <- ceiling(Nobs / N2star)
  Grps <- inverse.rle(list(lengths=rep(N2star, Ngrp), values=seq(Ngrp)))
  length(Grps) <- Nobs # Truncate if necessary
  ## Compute the fixed method
  Mins <- tapply(Flow, Grps, min)
  Fixed <- Mins[as.character(Grps)]
  ## Now the sliding method
  Slide <- sapply(seq(N2star, Nobs), function(i)
    min(Flow[seq(i - N2star + 1L, i)])
  )
  SlB <- Slide[1L]
  SlE <- Slide[length(Slide)]
  Nfil <- (N2star - 1L) / 2L
  Slide <- c(rep(SlB, Nfil), Slide, rep(SlE, Nfil))
  ## And the local minimum
  Mid <- as.integer((N2star) / 2)
  LocMin <- sapply(seq(N2star, Nobs), function(i)
    min(Flow[seq(i - N2star + 1L, i)]) == Flow[i - Mid]
  )
  LocMin <- c(rep(FALSE, Nfil), LocMin, rep(FALSE, Nfil))
  ## Need to trap short periods where only 1 local minimum
  if(sum(LocMin) == 1L) {
    warning("Only one local minimum in calibration period")
    LocMin <- pmax(Flow[LocMin], 0.01)
  } else
    LocMin <- exp(approx(which(LocMin), log(pmax(Flow[LocMin], 0.01)), xout=seq(Nobs), rule=2)$y)
  LocMin <- pmin(Flow, LocMin) # recover 0s and tails
  if(select == "fixed")
    BaseQ <- Fixed
  else if(select == "sliding")
    BaseQ <- Slide
  else 
    BaseQ <- LocMin
  retval <- data.frame(Dates=Dates, BaseQ=round(BaseQ, 3L), 
                       Flow=Flow, Fixed=Fixed, Sliding=Slide, 
                       LocalMin=LocMin)
  if(!is.null(STAID))
    attr(retval, "STAID") <- STAID
  attr(retval, "type") <- "hysep"
  class(retval) <- c("baseflow", "data.frame")
  return(retval)
}
```

#get Q in previous days to calculate storm index
```{r}
USGS_cc4$storm<-" "
for (i in c(1:length(USGS_cc4$USGS)))
#for (i in c(41:59))
{
siteNo <- as.character(USGS_cc4[i,]$USGS)
pCode <- "00060" #discharge
start.date <- as.character(as.Date(USGS_cc4[i,]$ActivityStartDate,format=("%Y-%m-%d"))-44)
end.date <- as.character(USGS_cc4[i,]$ActivityStartDate)

if (nrow(readNWISdv(siteNumbers = siteNo,
                     parameterCd = pCode,
                     startDate = start.date,
                     endDate = end.date))>0)
{
  print(nrow(readNWISdv(siteNumbers = siteNo,
                     parameterCd = pCode,
                     startDate = start.date,
                     endDate = end.date)))
  USGS_cc4[i,]$Q<- readNWISdv(siteNumbers = siteNo,
                     parameterCd = pCode,
                     startDate = end.date,
                     endDate = end.date)$X_00060_00003
  
 st<- paste("Q_44days",i,sep='_')
  st<- readNWISdv(siteNumbers = siteNo,
                     parameterCd = pCode,
                     startDate = start.date,
                     endDate = end.date)
  print (paste("Q_44days",i,sep='_'))
  #hysep(s1372500$X105182_00060_00003,Dates=2/1/2019,da=1)
  #head(s1372500)
  #agency_cd site_no datetime X105182_00060_00003 X105182_00060_00003_cd
#1      USGS 1372500 2/1/2019                 399                      P
test<-hysep(as.integer(st$X_00060_00003),Dates=
              #2008-09-27
              #9/27/2008
              st$Date
            ,da=1)
print(test)
USGS_cc4[i,]$storm<-(1-test$BaseQ[45]/test$Flow[45])
}
else
{
 USGS_cc4[i,]$storm<-NA 
 USGS_cc4[i,]$Q<-NA 
}
print(paste("day ",i," done",sep=','))
  }
head(USGS_cc4)
plot(USGS_cc4$storm,as.numeric(USGS_cc4$runoff))
                                
save(USGS_cc4,file="/Users/owner/Desktop/crypto/USGS_cc4_20190507_2.Rdata")
```

#merge the land use data
```{r}
load("/Users/owner/Desktop/bas_nonref_CntlPlains_cry_ws/bas_nonref_CntlPlains_cry_ws.Rdata")
load("/Users/owner/Desktop/bas_nonref_EastHghlnds_cry_ws/bas_nonref_EastHghlnds_cry_ws.Rdata")
load("/Users/owner/Desktop/bas_nonref_NorthEast_cry_ws/bas_nonref_NorthEast_cry_ws.Rdata")

USGS_cc4_lulc_CntlPlains<-merge(bas_nonref_CntlPlains_cry_ws,USGS_cc4,by.x="GAGE_ID", by.y="MonitoringLocationIdentifier")
USGS_cc4_lulc_EastHghlnds<-merge(bas_nonref_EastHghlnds_cry_ws,USGS_cc4,by.x="GAGE_ID", by.y="MonitoringLocationIdentifier" )
USGS_cc4_lulc_NorthEast<-merge(bas_nonref_NorthEast_cry_ws,USGS_cc4,by.x="GAGE_ID", by.y="MonitoringLocationIdentifier" )

USGS_cc4_lulc_CntlPlains_EastHghlnds_cry_ws<-rbind(USGS_cc4_lulc_CntlPlains,USGS_cc4_lulc_EastHghlnds)
USGS_cc4_lulc_CntlPlains_EastHghlnds_NorthEast_cry_ws<-rbind(USGS_cc4_lulc_NorthEast,USGS_cc4_lulc_CntlPlains_EastHghlnds_cry_ws)

dim(USGS_cc4_lulc_CntlPlains)
dim(USGS_cc4_lulc_CntlPlains_EastHghlnds_cry_ws)
dim(USGS_cc4_lulc_CntlPlains_EastHghlnds_NorthEast_cry_ws)

```


#split the data into training and test
```{r}

USGS_cc4_lulc<-USGS_cc4_lulc_CntlPlains_EastHghlnds_NorthEast_cry_ws

colnames(USGS_cc4_lulc)[colnames( USGS_cc4_lulc)=="TAVG"] <- "Temperature"
colnames(USGS_cc4_lulc)[colnames( USGS_cc4_lulc)=="storm"] <- "SurfaceQ"
colnames(USGS_cc4_lulc)[colnames( USGS_cc4_lulc)=="detect"] <- "Detect"
colnames(USGS_cc4_lulc)[colnames( USGS_cc4_lulc)=="DrainageAreaMeasure.MeasureValue"] <- "Watershed_Area"
colnames(USGS_cc4_lulc)[colnames( USGS_cc4_lulc)=="runoff"] <- "Runoff"

#Partitioning the data and running a GBM

#Creating training and test sets
set.seed(123) #uses a fixed seed so that every call will result in the same output.

USGS_cc4_lulc<-USGS_cc4_lulc[,c(47:48,44,42,36:38, 29,26)]

intrain<-createDataPartition(y=USGS_cc4_lulc$Detect ,
                             p=0.8,
                             list=FALSE)
#class(intrain) "matrix"

test<-USGS_cc4_lulc[-intrain,]
training<-USGS_cc4_lulc[intrain,]

dim(test)
dim(training)
```

#the model
```{r}
model<-as.formula(paste(colnames(USGS_cc4_lulc)[9], "~",      paste(colnames(USGS_cc4_lulc)[c(1:8)], collapse="+"), #families
                        sep = ""))
#that error message typically means you don’t have values for a variable represented in the model building process. 
water_gbm_lumped<- gbm(model,
             data=training, 
             distribution="bernoulli",
             n.trees=400,
             shrinkage=0.1,
             interaction.depth=1,
             bag.fraction=0.50,
             #train.fraction=1,
             n.minobsinnode=10,
             cv.folds=10, # that error occurs when you have variable levels that exist in the test set which don't exist in the training set.
             keep.data=TRUE,
             class.stratify.cv=TRUE,
             verbose="CV")
jpeg(paste("/Users/owner/Desktop/crypto/cry/","lumped_perf",'.jpg',sep=''))
gbm.perf(water_gbm_lumped)

```

#Partial dependence plots. 
```{r}
jpeg(paste("/Users/owner/Desktop/crypto/cry/","relative_influence",'.jpg',sep=''))
par(mar = c(5, 11, 1, 1))
summary(
 water_gbm_lumped , 
  cBars = 10,
  method = relative.influence, # also can use permutation.test.gbm
  las = 2
  )
dev.off()

jpeg(paste("/Users/owner/Desktop/crypto/cry/","SurfaceQ",'.jpg',sep=''))
water_gbm_lumped %>%
  partial(pred.var =  "SurfaceQ", n.trees = water_gbm_lumped$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = training)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24
                                #,face="bold"
                                ))
#+scale_y_continuous(labels = scales::dollar)
 #+scale_y_continuous(labels = scales::marginal effect )
dev.off()

jpeg(paste("/Users/owner/Desktop/crypto/cry/","Wetland",'.jpg',sep=''))
water_gbm_lumped %>%
  partial(pred.var =  "Wetland", n.trees = water_gbm_lumped$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = training)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24
                                #,face="bold"
                                ))
dev.off()

jpeg(paste("/Users/owner/Desktop/crypto/cry/","Temperature",'.jpg',sep=''))
water_gbm_lumped %>%
  partial(pred.var =  "Temperature", n.trees = water_gbm_lumped$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = training)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24
                                #,face="bold"
                                ))
dev.off()

jpeg(paste("/Users/owner/Desktop/crypto/cry/","Runoff",'.jpg',sep=''))
water_gbm_lumped %>%
  partial(pred.var =  "Runoff", n.trees = water_gbm_lumped$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = training)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24
                                #,face="bold"
                                ))
dev.off()

jpeg(paste("/Users/owner/Desktop/crypto/cry/","Forest",'.jpg',sep=''))
water_gbm_lumped %>%
  partial(pred.var =  "Forest", n.trees = water_gbm_lumped$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = training)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24
                                #,face="bold"
                                ))
dev.off()

jpeg(paste("/Users/owner/Desktop/crypto/cry/","Developed",'.jpg',sep=''))
water_gbm_lumped %>%
  partial(pred.var =  "Developed", n.trees = water_gbm_lumped$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = training)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24
                                #,face="bold"
                                ))
dev.off()

jpeg(paste("/Users/owner/Desktop/crypto/cry/","Cultivated",'.jpg',sep=''))
water_gbm_lumped %>%
  partial(pred.var =  "Cultivated", n.trees = water_gbm_lumped$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = training)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24
                                #,face="bold"
                                ))
dev.off()

jpeg(paste("/Users/owner/Desktop/crypto/cry/","Watershed_Area",'.jpg',sep=''))
water_gbm_lumped %>%
  partial(pred.var =  "Watershed_Area", n.trees = water_gbm_lumped$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = training)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24
                                #,face="bold"
                                ))
#partialPlot(boston.rf, pred.data = boston, x.var = "lstat",cex.lab=2.3)



```
